version: '3.8'

services:
  web:
    build: ./nicework
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./nicework/:/usr/src/nicework/
    ports:
      - 20080:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 25432:5432
    expose:
      - 5432
    environment:
      - POSTGRES_USER=donggyeong
      - POSTGRES_PASSWORD=saltlux#20

      - POSTGRES_DB=donggyeong_dev

volumes:
  postgres_data: