# Generated by Django 3.2.13 on 2022-05-18 19:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=40, unique=True, verbose_name='이메일')),
                ('realname', models.CharField(max_length=10, verbose_name='이름')),
                ('phonenum', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(regex='^01([0|1|6|7|8|9]?)-?([0-9]{3,4})-?([0-9]{4})$')], verbose_name='휴대폰 번호')),
                ('rank', models.CharField(choices=[('AS', '주임'), ('SN', '대리'), ('PC', '책임'), ('CF', '수석')], default='AS', max_length=2, verbose_name='직급')),
                ('department', models.CharField(choices=[('DEV', '개발팀'), ('KNG', '지식큐레이션팀')], default='KNG', max_length=3, verbose_name='부서')),
                ('effcdate', models.DateField(verbose_name='입사 일자')),
                ('openingtime', models.TimeField(verbose_name='평소 근무 시작시간')),
                ('closingtime', models.TimeField(verbose_name='평소 근무 종료시간')),
                ('adminmemo', models.TextField(blank=True, max_length=1000, null=True, verbose_name='관리자 메모')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_manager', models.BooleanField(default=False)),
                ('is_sbstt', models.BooleanField(default=True, verbose_name='연장근로 대체휴가 변환')),
                ('is_over80p', models.BooleanField(default=False, verbose_name='출근 1년간 80% 이상')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
