# Generated by Django 3.2.13 on 2022-05-18 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CmtHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weeknum', models.PositiveSmallIntegerField()),
                ('todaycat', models.CharField(choices=[('AL', '연차'), ('MO', '오전 반차'), ('AO', '오후 반차'), ('CV', '경조 휴가'), ('OL', '공가'), ('EL', '조퇴'), ('AB', '결근'), ('SL', '병가'), ('HD', '공휴일'), ('WE', '주말'), ('WD', '평일')], default='WD', max_length=2)),
                ('openingtime', models.TimeField(null=True)),
                ('closingtime', models.TimeField(null=True)),
                ('startdatetime', models.DateTimeField()),
                ('enddatetime', models.DateTimeField(blank=True, null=True)),
                ('workinghours', models.FloatField(default=0)),
                ('breaktime', models.FloatField(default=0)),
                ('overtime', models.FloatField(default=0)),
                ('is_abnormal', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
