# Generated by Django 3.2.13 on 2022-05-23 16:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('commute', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmthistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cmthistory',
            name='notice',
            field=models.TextField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cmthistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
