# Generated by Django 3.2.13 on 2022-05-23 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commute', '0002_auto_20220523_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmthistory',
            name='approval',
            field=models.CharField(choices=[('1', '대기'), ('2', '반려'), ('3', '승인')], default='1', max_length=1),
        ),
    ]
