# Generated by Django 3.2.13 on 2022-05-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commute', '0003_cmthistory_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmthistory',
            name='is_dayofflunch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cmthistory',
            name='is_ovtimedinner',
            field=models.BooleanField(default=False),
        ),
    ]
